### PR TITLE
Nvidia gpu profile

### PR DESCRIPTION
**Pull request by robsyme**
This PR adds the `accelerator` directive to the GPU-requiring tasks when `params.use_gpu` is set to true. 

When `use_gpu` is set to false, the directive is not set.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/proteinfold/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/proteinfold _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by drpatelh** [comment]
This process uses GPUs too so will need to do the same:
https://github.com/nf-core/proteinfold/blob/3eb9f4780f6bbe7be5d270f5e75da268e6a6d02d/conf/modules_alphafold2.config#L46

**Comment by athbaltzis** [comment]
The 'RUN_ALPHAFOLD2_MSA' process does not require GPUs, since it only computes the MSA and does not do any inference. So, we could leave as it is.

**Comment by drpatelh** [comment]
If we have tested this be great if we can get a patch release out so we don't need to use any external configuration when running the pipeline.

Be great if you can update the `CHANGELOG` too @robsyme

**Comment by drpatelh** [comment]
On second thoughts, whilst we are doing this and given that we have got it working via Tower Forge it might be worth setting up the CE in the nf-core Org on Tower and getting the automated tests to work. Will take a look next week.

**Review by drpatelh — APPROVED** [review]
Noice! 🕺🏽

**Pull request merged**
